# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import controle_pb2 as controle__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in controle_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControladorAmbienteStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessarLeitura = channel.unary_unary(
                '/smartenv.ControladorAmbiente/ProcessarLeitura',
                request_serializer=controle__pb2.SensorData.SerializeToString,
                response_deserializer=controle__pb2.ActuatorCommand.FromString,
                _registered_method=True)


class ControladorAmbienteServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessarLeitura(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControladorAmbienteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessarLeitura': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessarLeitura,
                    request_deserializer=controle__pb2.SensorData.FromString,
                    response_serializer=controle__pb2.ActuatorCommand.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smartenv.ControladorAmbiente', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('smartenv.ControladorAmbiente', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControladorAmbiente(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessarLeitura(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartenv.ControladorAmbiente/ProcessarLeitura',
            controle__pb2.SensorData.SerializeToString,
            controle__pb2.ActuatorCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
